FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY *.sln ./
COPY src/AspNetCore.Mvc.Fragments/AspNetCore.Mvc.Fragments/*.csproj ./src/AspNetCore.Mvc.Fragments/AspNetCore.Mvc.Fragments/
COPY demo/AspNetCore.Mvc.Fragments.Demo/AspNetCore.Mvc.Fragments.Demo/*.csproj ./demo/AspNetCore.Mvc.Fragments.Demo/AspNetCore.Mvc.Fragments.Demo/
COPY demo/AspNetCore.Mvc.Fragments.Demo.FragmentSource1/*.csproj ./demo/AspNetCore.Mvc.Fragments.Demo.FragmentSource1/
COPY demo/AspNetCore.Mvc.Fragments.Demo.FragmentSource2/*.csproj ./demo/AspNetCore.Mvc.Fragments.Demo.FragmentSource2/

RUN dotnet restore
COPY . .

WORKDIR /src/src/AspNetCore.Mvc.Fragments/AspNetCore.Mvc.Fragments
RUN dotnet build -c Release -o /app

WORKDIR /src/demo/AspNetCore.Mvc.Fragments.Demo.FragmentSource1
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "AspNetCore.Mvc.Fragments.Demo.FragmentSource1.dll"]